name: thesis_harshal_talsania_martin_becker
channels:
  - defaults
dependencies:
  - python=3.11.5
  - ipykernel
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - shap 
  - jupyter
  - statsmodels
  - pip:
    - tensorflow==2.15.0
    - tensorflow-probability==0.23.0
    - tensorflow-addons==0.22.0
    - jenkspy==0.4.0
    - torch==2.1.1
    - kneed==0.7.0 
